version: "1"

rules:
  - base: systemverilog
    upstream: wei:master
    mergeMethod: merge
    mergeUnstable: false
  - base: c
    upstream: wei:master
    mergeMethod: merge
    mergeUnstable: false
    
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict"
